### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by PeterKW** [MehrinFirdousi/Synaera-TeamSemaphore#1]
https://apt.izzysoft.de/fdroid/index/apk/com.example.synaera

Is this the latest version?

**Comment by PeterKW** [comment]
Doesn't seem to do much

**Comment by IzzySoft** [comment]
> Doesn't seem to do much

You mean the app doesn't do much, @PeterKW?

@MehrinFirdousi there's one more issue with the APK: a scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Are you still maintaining this app? Thanks in advance!

**Comment by IzzySoft** [comment]
@MehrinFirdousi any word?

**Comment by AdamJeddy** [comment]
@IzzySoft This app is currently not being maintained

**Comment by IzzySoft** [comment]
Thanks @AdamJeddy – that means I'll have to unlist it from [my repo](https://apt.izzysoft.de/fdroid) – at least temporarily until development is picked up again. Please reach out to me when that time comes, so I can list it again. Thanks!
